### ISSUE TITLE
Generator stop after Step - Project Repo-URL

### ISSUE THREAD

**Issue by Kevinci** [kittn/generator-kittn#27]
With Installing WP-CLI manually it works.

` URL to the Git-Repo 
error connecting: Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    --------------------
    at Protocol._enqueue (/Users/deadpool/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/Users/deadpool/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/Users/deadpool/node_modules/mysql/lib/Connection.js:130:18)
    at yeoman.Base.extend.app (/Users/deadpool/node_modules/generator-kittn/app/index.js:624:18)
    at Object.<anonymous> (/Users/deadpool/node_modules/yeoman-generator/lib/base.js:439:23)
    at /Users/deadpool/node_modules/run-async/index.js:25:25
    at /Users/deadpool/node_modules/run-async/index.js:24:19
    at /Users/deadpool/node_modules/yeoman-generator/lib/base.js:440:9
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback/Users/deadpool/node_modules/generator-kittn/app/index.js:632
        if (error) throw error;
                   ^
Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
    --------------------
    at Protocol._enqueue (/Users/deadpool/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/Users/deadpool/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/Users/deadpool/node_modules/mysql/lib/Connection.js:130:18)
    at yeoman.Base.extend.app (/Users/deadpool/node_modules/generator-kittn/app/index.js:624:18)
    at Object.<anonymous> (/Users/deadpool/node_modules/yeoman-generator/lib/base.js:439:23)
    at /Users/deadpool/node_modules/run-async/index.js:25:25
    at /Users/deadpool/node_modules/run-async/index.js:24:19
    at /Users/deadpool/node_modules/yeoman-generator/lib/b%     `

**Comment by CinKon** [comment]
```bash
Project Repo-URL
  URL to the Git-Repo CinKon
events.js:160
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected identifier in /Applications/MAMP/htdocs/_Vorlagen/generator-kittn/app/templates/_config.json while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
    at new Function (<anonymous>)
    at Template.compile (/Applications/MAMP/htdocs/_Vorlagen/generator-kittn/node_modules/ejs/lib/ejs.js:481:12)
    at Object.compile (/Applications/MAMP/htdocs/_Vorlagen/generator-kittn/node_modules/ejs/lib/ejs.js:290:16)
    at handleCache (/Applications/MAMP/htdocs/_Vorlagen/generator-kittn/node_modules/ejs/lib/ejs.js:168:18)
    at Object.exports.render (/Applications/MAMP/htdocs/_Vorlagen/generator-kittn/node_modules/ejs/lib/ejs.js:316:10)
    at process (/Applications/MAMP/htdocs/_Vorlagen/generator-kittn/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
    at applyProcessingFunc (/Applications/MAMP/htdocs/_Vorlagen/generator-kittn/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/Applications/MAMP/htdocs/_Vorlagen/generator-kittn/node_modules/mem-fs-editor/lib/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/Applications/MAMP/htdocs/_Vorlagen/generator-kittn/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Applications/MAMP/htdocs/_Vorlagen/generator-kittn/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
```

**Comment by CinKon** [comment]
@Kevinci what Repo-URL did you use?

**Comment by Kevinci** [comment]
@CinKon empty

**Comment by CinKon** [comment]
Fixed
